# åº”ç”¨åŸºç¡€é…ç½®
app:
  name: "app" # åº”ç”¨åç§°
  env: "dev" # åº”ç”¨ç¯å¢ƒ dev|test|prod

# HTTP æœåŠ¡é…ç½®
http_server:
  addr: ":8888"
  log:
    # ä»…åœ¨æœ¬åœ°å¼€å‘è°ƒè¯•æ—¶æ‰“å¼€
    # access_filename: "/dev/stdout"
    # error_filename: "/dev/stderr"

# ä¸šåŠ¡ç§æœ‰é…ç½®
biz:

# åº”ç”¨ä¸šåŠ¡æ—¥å¿—é…ç½®
log:
  level: 4 # æ—¥å¿—çº§åˆ« 0: panic 1: fatal 2: error 3: warn 4: info 5: debug 6: trace
  # ä»…åœ¨æœ¬åœ°å¼€å‘è°ƒè¯•æ—¶æ‰“å¼€
  # filename: "/dev/stdout"

# HTTP Client é…ç½®
resty:
  timeout: "5s"

# è·¨åŸŸä¸­é—´ä»¶é…ç½?
mid_cors:
  allow_origins: [
      # æœ¬åœ°/æµ‹è¯•ç­‰ç¯å¢ƒé…ç½?æ­£å¼ç¯å¢ƒé¡»å»é™?
      "*",
      "https://test.*.com",

      # ç”Ÿäº§ç¯å¢ƒé…ç½®
      "https://prod.*.com",
    ]

# æ•°æ®åº“é…ç½?
db:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "Ljw030710"
  database: "biaobai"

# # Redis é…ç½® å¼€å¯å‰è¯·åœ¨ register/boot.go ä¸­è¿›è¡?nedis.Boot()
# redis:
#   addrs:
#     - "127.0.0.1:6379"
#   db: 0
#   password: "jh_pass"

# é£ä¹¦å‘Šè­¦é…ç½®
feishu:
  enable: false
  notice_webhook: ""
  notice_secret: ""
#ä¸ƒç‰›äº‘é…ç½?
qiniu:
  access_key: "7Esv5lWwgMhEoCUnuJbCY-oDTnijXgRzll5oNCZh"
  secret_key: "QdLH0zgtZyMt8bCxSPdFXT4zLtwYEiJkTZLjv4Fa"
  bucket: "repoaa"
  domain: "http://ta4qfny94.hd-bkt.clouddn.com/"
